### ISSUE TITLE
Wrong name for FreeTTS jar

### ISSUE THREAD

**Issue by FlorianRas** [JVoiceXML/cairo#52]
I modified the synthetiser in cairo-config file from  **<speechSynthesizer>Mary</speechSynthesizer>** to  **<speechSynthesizer>FreeTTS</speechSynthesizer>** but with this configuration, Cairo was looking for a jar file named "freetts.jar" which does not exist:

`  1488 [main                ] ERROR                     System.err (   748) [] java.io.FileNotFoundException: C:\Users\Florian\Downloads\cairo-0.3.1\org.speechforge.cairo.server-0.3.1\lib\freetts.jar (The system cannot find the file specified)`

I had to rename an existing jar file named "freetts-0.1.jar" to "freetts.jar" and it worked.

**Comment by schnelle** [comment]
Previously used FreeTTS jars was outdated.  Switched to using the jars from te official FreeTTS Gradle repro to make it work again.
Additionally, the provided related jars for voices are alos now taken from the Gradle repository.
